@Library('corda-shared-build-pipeline-steps@mbrkic-r3/CORE-16243/persistence-worker') _
// TODO revert to 5.1 after branch above is merged to it
// @Library('corda-shared-build-pipeline-steps@5.1') _

ethereumInterop(
    deployEthereum: true,
)
