/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.corda.p2p;
@org.apache.avro.specific.AvroGenerated
public enum NetworkType implements org.apache.avro.generic.GenericEnumSymbol<NetworkType> {
  CORDA_4, CORDA_5  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NetworkType\",\"namespace\":\"net.corda.p2p\",\"symbols\":[\"CORDA_4\",\"CORDA_5\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
