imagePullPolicy: IfNotPresent
image:
  registry: corda-os-docker-dev.software.r3.com
  tag: latest-local

kafka:
  bootstrapServers: prereqs-kafka:9092

db:
  cluster:
    host: prereqs-postgresql.corda # NOTE: corda here is the current namespace, change in case you are deploying to a different
    existingSecret: prereqs-postgresql