# values file suitable for local deployment of the corda helm chart.
#
# First use `./gradlew publishOSGiImage --parallel` to create local docker images
# Then deploy using:
#
#  helm upgrade --install corda -n corda \
#  charts/corda \
#  --values values.yaml \
#  --values debug.yaml \
#  --wait
#
# See `debug.yaml` for debug settings
imagePullPolicy: IfNotPresent
image:
  registry: corda-os-docker-dev.software.r3.com
  tag: latest-local

kafka:
  bootstrapServers: prereqs-kafka:9092
  replicas: 1
  tls:
    enabled: false
    truststore:
      secretRef:
        name: prereqs-kafka-0-tls

db:
  cluster:
    host: prereqs-postgresql.corda # NOTE: corda here is the current namespace, change in case you are deploying to a different 
    existingSecret: prereqs-postgresql
