# values file suitable for local deployment of the corda helm chart.
#
# First use `./gradlew publishOSGiImage --parallel` to create local docker images
# Then deploy using:
#
#  helm upgrade --install corda -n corda \
#  charts/corda \
#  --values values.yaml \
#  --values debug.yaml \
#  --wait
#
# See `debug.yaml` for debug settings
# NOTE: The below assumes you deploy Kafka and the PostgreSQL database in the same namespace, so that domain names containing just the service name are resolved (i.e. prereqs-postgresql instead of prereqs-postgresql.<namespace>)
#       If that is not the case, you might need to add the namespace as a suffix.
imagePullPolicy: "IfNotPresent"
image:
  registry: "corda-os-docker-dev.software.r3.com"
  tag: "latest-local"

logging:
  format: "text"
  level: "info"

bootstrap:
  initialAdminUser:
    password:
      value: "admin"
  kafka:
    replicas: 1

kafka:
  bootstrapServers: "prereqs-kafka:9092"
  sasl:
    enabled: true
    username:
      value: "user"
    password:
      valueFrom:
        secretKeyRef:
          name: "prereqs-kafka-jaas"
          key: "client-passwords"
  tls:
    enabled: true
    truststore:
      valueFrom:
        secretKeyRef:
          name: "prereqs-kafka-0-tls"
          key: "ca.crt"

db:
  cluster:
    host: "prereqs-postgresql"
    password:
      valueFrom:
        secretKeyRef:
          name: "prereqs-postgresql"
          key: "password"
    username:
      value: "user"
