# values file suitable for local deployment of the corda helm chart.
#
# First use `./gradlew publishOSGiImage --parallel` to create local docker images
# Then deploy using:
#
#  helm upgrade --install corda -n corda \
#  charts/corda \
#  --values values.yaml \
#  --values debug.yaml \
#  --wait
#
# See `debug.yaml` for debug settings
# NOTE: The below assumes you deploy Kafka and the PostgreSQL database in the same namespace, so that domain names containing just the service name are resolved (i.e. prereqs-postgresql instead of prereqs-postgresql.<namespace>)
#       If that is not the case, you might need to add the namespace as a suffix.
imagePullPolicy: IfNotPresent
image:
  registry: corda-os-docker-dev.software.r3.com
  tag: latest-local

logging:
  format: "text"
  level: "info"

bootstrap:
  initialAdminUser:
    password: "admin"
  kafka:
    replicas: 1

kafka:
  bootstrapServers: prereqs-kafka:9092
  tls:
    enabled: true
    truststore:
      secretRef:
        name: prereqs-kafka-0-tls

db:
  cluster:
    host: prereqs-postgresql
    existingSecret: prereqs-postgresql
