{
 "title": "Corda Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Server Requests Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(corda_http_server_request_time_seconds_sum[$__rate_interval]) / rate(corda_http_server_request_time_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Server Requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "corda_http_server_request_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sandbox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Sandbox creation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(corda_sandbox_create_time_seconds_sum[$__rate_interval]) / rate(corda_sandbox_create_time_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max sandbox creation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "corda_sandbox_create_time_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cache Put",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "cache_puts_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "cache_gets_total{result=\"hit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "cache_gets_total{result=\"miss\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Eviction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "cache_evictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "cache_size", "legendFormat": "__auto" }
   ]
  }
 ]
}