/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.corda.data;
@org.apache.avro.specific.FixedSize(32)
@org.apache.avro.specific.AvroGenerated
public class Fingerprint extends org.apache.avro.specific.SpecificFixed {
  private static final long serialVersionUID = -3182778082645344425L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"Fingerprint\",\"namespace\":\"net.corda.data\",\"size\":32}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  /** Creates a new Fingerprint */
  public Fingerprint() {
    super();
  }

  /**
   * Creates a new Fingerprint with the given bytes.
   * @param bytes The bytes to create the new Fingerprint.
   */
  public Fingerprint(byte[] bytes) {
    super(bytes);
  }

  private static final org.apache.avro.io.DatumWriter<Fingerprint>
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter<Fingerprint>(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader<Fingerprint>
    READER$ = new org.apache.avro.specific.SpecificDatumReader<Fingerprint>(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
