@Library('existing-build-control')
import static com.r3.build.BuildControl.killAllExistingBuildsForJob
killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

/**
 * Sense environment
 */

pipeline {
    agent {
        docker {
            // Our custom docker image
            image 'build-zulu-openjdk:11'
            label 'docker'
            registryUrl 'https://engineering-docker.software.r3.com/'
            registryCredentialsId 'artifactory-credentials'
            // Used to mount storage from the host as a volume to persist the cache between builds
            args '-v /tmp:/host_tmp'
        }
    }

    options {
        ansiColor('xterm')
        timestamps()
        timeout(3*60) // 3 hours
        skipDefaultCheckout(true)
    }

    environment {
        EXECUTOR_NUMBER = "${env.EXECUTOR_NUMBER}"
        ARTIFACTORY_CREDENTIALS = credentials('artifactory-credentials')
        CORDA_ARTIFACTORY_USERNAME = "${env.ARTIFACTORY_CREDENTIALS_USR}"
        CORDA_ARTIFACTORY_PASSWORD = "${env.ARTIFACTORY_CREDENTIALS_PSW}"
        ARTIFACTORY_BUILD_NAME = "Flow worker/Jenkins/${env.BRANCH_NAME}".replaceAll("/", " :: ")
        GRADLE_USER_HOME = "/host_tmp/gradle"
    }

    stages {

         stage('Checkout Custom') {
            steps {
                checkout([
                	$class: 'GitSCM',
                	branches: scm.branches,
                	doGenerateSubmoduleConfigurations: scm.doGenerateSubmoduleConfigurations,
                	extensions: scm.extensions + [[$class: 'CloneOption', noTags: false, reference: '', shallow: true]],
                	submoduleCfg: [],
                	userRemoteConfigs: scm.userRemoteConfigs
                ])
            }
        }

        stage('Release modules') {
            steps {
                sh "./gradlew helloworld:release -Prelease.customUsername=\"LWogan\" -Prelease.customPassword=\"cb3d93f2771bdac74cfcfac527f330596cc97aac\" "
                sh "./gradlew helloworld-impl:release -Prelease.customUsername=\"LWogan\" -Prelease.customPassword=\"cb3d93f2771bdac74cfcfac527f330596cc97aac\" "
                sh "./gradlew goodbyeworld:release -Prelease.customUsername=\"LWogan\" -Prelease.customPassword=\"cb3d93f2771bdac74cfcfac527f330596cc97aac\" "
            }
        }
        stage('Create JARs') {
            steps {
                sh "./gradlew jar"
            }
        }

        stage('Publish to Artifactory') {
            steps {
                rtServer(
                        id: 'R3-Artifactory',
                        url: 'https://software.r3.com/artifactory',
                        credentialsId: 'artifactory-credentials'
                )
                rtGradleDeployer(
                        id: 'deployer',
                        serverId: 'R3-Artifactory',
                        repo: 'r3-corda-releases'
                )
                rtGradleRun(
                        usesPlugin: true,
                        useWrapper: true,
                        switches: '-s --info',
                        tasks: 'artifactoryPublish',
                        deployerId: 'deployer',
                        buildName: env.ARTIFACTORY_BUILD_NAME
                )
                rtPublishBuildInfo(
                        serverId: 'R3-Artifactory',
                        buildName: env.ARTIFACTORY_BUILD_NAME
                )
            }
        }
    }

    post {
        cleanup {
            deleteDir() /* clean up our workspace */
        }
    }
}
