/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.corda.p2p.crypto.internal;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ResponderHandshakePayload extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7451827784662834875L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ResponderHandshakePayload\",\"namespace\":\"net.corda.p2p.crypto.internal\",\"fields\":[{\"name\":\"responderEncryptedExtensions\",\"type\":{\"type\":\"record\",\"name\":\"ResponderEncryptedExtensions\",\"fields\":[{\"name\":\"maxMessageSize\",\"type\":\"int\"}]}},{\"name\":\"responderPublicKeyHash\",\"type\":\"bytes\"},{\"name\":\"responderPartyVerify\",\"type\":\"bytes\"},{\"name\":\"responderFinished\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ResponderHandshakePayload> ENCODER =
      new BinaryMessageEncoder<ResponderHandshakePayload>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ResponderHandshakePayload> DECODER =
      new BinaryMessageDecoder<ResponderHandshakePayload>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ResponderHandshakePayload> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ResponderHandshakePayload> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ResponderHandshakePayload> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ResponderHandshakePayload>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ResponderHandshakePayload to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ResponderHandshakePayload from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ResponderHandshakePayload instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ResponderHandshakePayload fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private net.corda.p2p.crypto.internal.ResponderEncryptedExtensions responderEncryptedExtensions;
   private java.nio.ByteBuffer responderPublicKeyHash;
   private java.nio.ByteBuffer responderPartyVerify;
   private java.nio.ByteBuffer responderFinished;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ResponderHandshakePayload() {}

  /**
   * All-args constructor.
   * @param responderEncryptedExtensions The new value for responderEncryptedExtensions
   * @param responderPublicKeyHash The new value for responderPublicKeyHash
   * @param responderPartyVerify The new value for responderPartyVerify
   * @param responderFinished The new value for responderFinished
   */
  public ResponderHandshakePayload(net.corda.p2p.crypto.internal.ResponderEncryptedExtensions responderEncryptedExtensions, java.nio.ByteBuffer responderPublicKeyHash, java.nio.ByteBuffer responderPartyVerify, java.nio.ByteBuffer responderFinished) {
    this.responderEncryptedExtensions = responderEncryptedExtensions;
    this.responderPublicKeyHash = responderPublicKeyHash;
    this.responderPartyVerify = responderPartyVerify;
    this.responderFinished = responderFinished;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return responderEncryptedExtensions;
    case 1: return responderPublicKeyHash;
    case 2: return responderPartyVerify;
    case 3: return responderFinished;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: responderEncryptedExtensions = (net.corda.p2p.crypto.internal.ResponderEncryptedExtensions)value$; break;
    case 1: responderPublicKeyHash = (java.nio.ByteBuffer)value$; break;
    case 2: responderPartyVerify = (java.nio.ByteBuffer)value$; break;
    case 3: responderFinished = (java.nio.ByteBuffer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'responderEncryptedExtensions' field.
   * @return The value of the 'responderEncryptedExtensions' field.
   */
  public net.corda.p2p.crypto.internal.ResponderEncryptedExtensions getResponderEncryptedExtensions() {
    return responderEncryptedExtensions;
  }


  /**
   * Sets the value of the 'responderEncryptedExtensions' field.
   * @param value the value to set.
   */
  public void setResponderEncryptedExtensions(net.corda.p2p.crypto.internal.ResponderEncryptedExtensions value) {
    this.responderEncryptedExtensions = value;
  }

  /**
   * Gets the value of the 'responderPublicKeyHash' field.
   * @return The value of the 'responderPublicKeyHash' field.
   */
  public java.nio.ByteBuffer getResponderPublicKeyHash() {
    return responderPublicKeyHash;
  }


  /**
   * Sets the value of the 'responderPublicKeyHash' field.
   * @param value the value to set.
   */
  public void setResponderPublicKeyHash(java.nio.ByteBuffer value) {
    this.responderPublicKeyHash = value;
  }

  /**
   * Gets the value of the 'responderPartyVerify' field.
   * @return The value of the 'responderPartyVerify' field.
   */
  public java.nio.ByteBuffer getResponderPartyVerify() {
    return responderPartyVerify;
  }


  /**
   * Sets the value of the 'responderPartyVerify' field.
   * @param value the value to set.
   */
  public void setResponderPartyVerify(java.nio.ByteBuffer value) {
    this.responderPartyVerify = value;
  }

  /**
   * Gets the value of the 'responderFinished' field.
   * @return The value of the 'responderFinished' field.
   */
  public java.nio.ByteBuffer getResponderFinished() {
    return responderFinished;
  }


  /**
   * Sets the value of the 'responderFinished' field.
   * @param value the value to set.
   */
  public void setResponderFinished(java.nio.ByteBuffer value) {
    this.responderFinished = value;
  }

  /**
   * Creates a new ResponderHandshakePayload RecordBuilder.
   * @return A new ResponderHandshakePayload RecordBuilder
   */
  public static net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder newBuilder() {
    return new net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder();
  }

  /**
   * Creates a new ResponderHandshakePayload RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ResponderHandshakePayload RecordBuilder
   */
  public static net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder newBuilder(net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder other) {
    if (other == null) {
      return new net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder();
    } else {
      return new net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder(other);
    }
  }

  /**
   * Creates a new ResponderHandshakePayload RecordBuilder by copying an existing ResponderHandshakePayload instance.
   * @param other The existing instance to copy.
   * @return A new ResponderHandshakePayload RecordBuilder
   */
  public static net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder newBuilder(net.corda.p2p.crypto.internal.ResponderHandshakePayload other) {
    if (other == null) {
      return new net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder();
    } else {
      return new net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder(other);
    }
  }

  /**
   * RecordBuilder for ResponderHandshakePayload instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ResponderHandshakePayload>
    implements org.apache.avro.data.RecordBuilder<ResponderHandshakePayload> {

    private net.corda.p2p.crypto.internal.ResponderEncryptedExtensions responderEncryptedExtensions;
    private net.corda.p2p.crypto.internal.ResponderEncryptedExtensions.Builder responderEncryptedExtensionsBuilder;
    private java.nio.ByteBuffer responderPublicKeyHash;
    private java.nio.ByteBuffer responderPartyVerify;
    private java.nio.ByteBuffer responderFinished;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.responderEncryptedExtensions)) {
        this.responderEncryptedExtensions = data().deepCopy(fields()[0].schema(), other.responderEncryptedExtensions);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasResponderEncryptedExtensionsBuilder()) {
        this.responderEncryptedExtensionsBuilder = net.corda.p2p.crypto.internal.ResponderEncryptedExtensions.newBuilder(other.getResponderEncryptedExtensionsBuilder());
      }
      if (isValidValue(fields()[1], other.responderPublicKeyHash)) {
        this.responderPublicKeyHash = data().deepCopy(fields()[1].schema(), other.responderPublicKeyHash);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.responderPartyVerify)) {
        this.responderPartyVerify = data().deepCopy(fields()[2].schema(), other.responderPartyVerify);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.responderFinished)) {
        this.responderFinished = data().deepCopy(fields()[3].schema(), other.responderFinished);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ResponderHandshakePayload instance
     * @param other The existing instance to copy.
     */
    private Builder(net.corda.p2p.crypto.internal.ResponderHandshakePayload other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.responderEncryptedExtensions)) {
        this.responderEncryptedExtensions = data().deepCopy(fields()[0].schema(), other.responderEncryptedExtensions);
        fieldSetFlags()[0] = true;
      }
      this.responderEncryptedExtensionsBuilder = null;
      if (isValidValue(fields()[1], other.responderPublicKeyHash)) {
        this.responderPublicKeyHash = data().deepCopy(fields()[1].schema(), other.responderPublicKeyHash);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.responderPartyVerify)) {
        this.responderPartyVerify = data().deepCopy(fields()[2].schema(), other.responderPartyVerify);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.responderFinished)) {
        this.responderFinished = data().deepCopy(fields()[3].schema(), other.responderFinished);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'responderEncryptedExtensions' field.
      * @return The value.
      */
    public net.corda.p2p.crypto.internal.ResponderEncryptedExtensions getResponderEncryptedExtensions() {
      return responderEncryptedExtensions;
    }


    /**
      * Sets the value of the 'responderEncryptedExtensions' field.
      * @param value The value of 'responderEncryptedExtensions'.
      * @return This builder.
      */
    public net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder setResponderEncryptedExtensions(net.corda.p2p.crypto.internal.ResponderEncryptedExtensions value) {
      validate(fields()[0], value);
      this.responderEncryptedExtensionsBuilder = null;
      this.responderEncryptedExtensions = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'responderEncryptedExtensions' field has been set.
      * @return True if the 'responderEncryptedExtensions' field has been set, false otherwise.
      */
    public boolean hasResponderEncryptedExtensions() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'responderEncryptedExtensions' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public net.corda.p2p.crypto.internal.ResponderEncryptedExtensions.Builder getResponderEncryptedExtensionsBuilder() {
      if (responderEncryptedExtensionsBuilder == null) {
        if (hasResponderEncryptedExtensions()) {
          setResponderEncryptedExtensionsBuilder(net.corda.p2p.crypto.internal.ResponderEncryptedExtensions.newBuilder(responderEncryptedExtensions));
        } else {
          setResponderEncryptedExtensionsBuilder(net.corda.p2p.crypto.internal.ResponderEncryptedExtensions.newBuilder());
        }
      }
      return responderEncryptedExtensionsBuilder;
    }

    /**
     * Sets the Builder instance for the 'responderEncryptedExtensions' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder setResponderEncryptedExtensionsBuilder(net.corda.p2p.crypto.internal.ResponderEncryptedExtensions.Builder value) {
      clearResponderEncryptedExtensions();
      responderEncryptedExtensionsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'responderEncryptedExtensions' field has an active Builder instance
     * @return True if the 'responderEncryptedExtensions' field has an active Builder instance
     */
    public boolean hasResponderEncryptedExtensionsBuilder() {
      return responderEncryptedExtensionsBuilder != null;
    }

    /**
      * Clears the value of the 'responderEncryptedExtensions' field.
      * @return This builder.
      */
    public net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder clearResponderEncryptedExtensions() {
      responderEncryptedExtensions = null;
      responderEncryptedExtensionsBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'responderPublicKeyHash' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getResponderPublicKeyHash() {
      return responderPublicKeyHash;
    }


    /**
      * Sets the value of the 'responderPublicKeyHash' field.
      * @param value The value of 'responderPublicKeyHash'.
      * @return This builder.
      */
    public net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder setResponderPublicKeyHash(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.responderPublicKeyHash = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'responderPublicKeyHash' field has been set.
      * @return True if the 'responderPublicKeyHash' field has been set, false otherwise.
      */
    public boolean hasResponderPublicKeyHash() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'responderPublicKeyHash' field.
      * @return This builder.
      */
    public net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder clearResponderPublicKeyHash() {
      responderPublicKeyHash = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'responderPartyVerify' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getResponderPartyVerify() {
      return responderPartyVerify;
    }


    /**
      * Sets the value of the 'responderPartyVerify' field.
      * @param value The value of 'responderPartyVerify'.
      * @return This builder.
      */
    public net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder setResponderPartyVerify(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.responderPartyVerify = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'responderPartyVerify' field has been set.
      * @return True if the 'responderPartyVerify' field has been set, false otherwise.
      */
    public boolean hasResponderPartyVerify() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'responderPartyVerify' field.
      * @return This builder.
      */
    public net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder clearResponderPartyVerify() {
      responderPartyVerify = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'responderFinished' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getResponderFinished() {
      return responderFinished;
    }


    /**
      * Sets the value of the 'responderFinished' field.
      * @param value The value of 'responderFinished'.
      * @return This builder.
      */
    public net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder setResponderFinished(java.nio.ByteBuffer value) {
      validate(fields()[3], value);
      this.responderFinished = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'responderFinished' field has been set.
      * @return True if the 'responderFinished' field has been set, false otherwise.
      */
    public boolean hasResponderFinished() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'responderFinished' field.
      * @return This builder.
      */
    public net.corda.p2p.crypto.internal.ResponderHandshakePayload.Builder clearResponderFinished() {
      responderFinished = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ResponderHandshakePayload build() {
      try {
        ResponderHandshakePayload record = new ResponderHandshakePayload();
        if (responderEncryptedExtensionsBuilder != null) {
          try {
            record.responderEncryptedExtensions = this.responderEncryptedExtensionsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("responderEncryptedExtensions"));
            throw e;
          }
        } else {
          record.responderEncryptedExtensions = fieldSetFlags()[0] ? this.responderEncryptedExtensions : (net.corda.p2p.crypto.internal.ResponderEncryptedExtensions) defaultValue(fields()[0]);
        }
        record.responderPublicKeyHash = fieldSetFlags()[1] ? this.responderPublicKeyHash : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        record.responderPartyVerify = fieldSetFlags()[2] ? this.responderPartyVerify : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        record.responderFinished = fieldSetFlags()[3] ? this.responderFinished : (java.nio.ByteBuffer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ResponderHandshakePayload>
    WRITER$ = (org.apache.avro.io.DatumWriter<ResponderHandshakePayload>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ResponderHandshakePayload>
    READER$ = (org.apache.avro.io.DatumReader<ResponderHandshakePayload>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.responderEncryptedExtensions.customEncode(out);

    out.writeBytes(this.responderPublicKeyHash);

    out.writeBytes(this.responderPartyVerify);

    out.writeBytes(this.responderFinished);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.responderEncryptedExtensions == null) {
        this.responderEncryptedExtensions = new net.corda.p2p.crypto.internal.ResponderEncryptedExtensions();
      }
      this.responderEncryptedExtensions.customDecode(in);

      this.responderPublicKeyHash = in.readBytes(this.responderPublicKeyHash);

      this.responderPartyVerify = in.readBytes(this.responderPartyVerify);

      this.responderFinished = in.readBytes(this.responderFinished);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.responderEncryptedExtensions == null) {
            this.responderEncryptedExtensions = new net.corda.p2p.crypto.internal.ResponderEncryptedExtensions();
          }
          this.responderEncryptedExtensions.customDecode(in);
          break;

        case 1:
          this.responderPublicKeyHash = in.readBytes(this.responderPublicKeyHash);
          break;

        case 2:
          this.responderPartyVerify = in.readBytes(this.responderPartyVerify);
          break;

        case 3:
          this.responderFinished = in.readBytes(this.responderFinished);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










