package net.corda.applications.workers.db.test

internal const val FLAG_INSTANCE_ID = "-i"
internal const val FLAG_TOPIC_PREFIX = "-t"
internal const val FLAG_MAX_SIZE = "-M"
internal const val FLAG_DISABLE_MONITOR = "-n"
internal const val FLAG_MONITOR_PORT = "-p"
internal const val FLAG_MSG_PARAM = "-m"
internal const val FLAG_DB_PARAM = "-d"
internal const val FLAG_ADDITIONAL_PARAM = "-c"
internal const val FLAG_RECONCILIATION_TASKS_PARAM = "-r"

internal const val VAL_INSTANCE_ID = "123"
internal const val VALUE_TOPIC_PREFIX = "abc"
internal const val VALUE_MAX_SIZE = "1000000"
internal const val MSG_KEY_ONE = "msgKeyOne"
internal const val MSG_VAL_ONE = "msgValOne"
internal const val MSG_KEY_TWO = "msgKeyTwo"
internal const val MSG_VAL_TWO = "msgValTwo"
internal const val DB_KEY_ONE = "dbKeyOne"
internal const val DB_VAL_ONE = "dbValOne"
internal const val DB_KEY_TWO = "dbKeyTwo"
internal const val DB_VAL_TWO = "dbValTwo"
internal const val CUSTOM_KEY_ONE = "customKeyOne"
internal const val CUSTOM_VAL_ONE = "customValOne"
internal const val CUSTOM_KEY_TWO = "customKeyTwo"
internal const val CUSTOM_VAL_TWO = "customValTwo"
internal const val WORKSPACE_DIR = "dir.workspace"
internal const val TEMP_DIR = "dir.tmp"

internal const val DEFAULT_TOPIC_PREFIX = ""
internal const val CUSTOM_CONFIG_PATH = "custom"