package net.corda.applications.workers.db.test

internal const val FLAG_INSTANCE_ID = "-i"
internal const val FLAG_TOPIC_PREFIX = "-t"
internal const val FLAG_DISABLE_MONITOR = "-n"
internal const val FLAG_MONITOR_PORT = "-p"
internal const val FLAG_MSG_PARAM = "-m"
internal const val FLAG_DB_PARAM = "-d"
internal const val FLAG_ADDITIONAL_PARAM = "-c"

internal const val KEY_INSTANCE_ID = "instanceId"
internal const val VAL_INSTANCE_ID = "123"
internal const val KEY_TOPIC_PREFIX = "messaging.topic.prefix"
internal const val VALUE_TOPIC_PREFIX = "abc"
internal const val MSG_KEY_ONE = "msgKeyOne"
internal const val MSG_VAL_ONE = "msgValOne"
internal const val MSG_KEY_TWO = "msgKeyTwo"
internal const val MSG_VAL_TWO = "msgValTwo"
internal const val DB_KEY_ONE = "dbKeyOne"
internal const val DB_VAL_ONE = "dbValOne"
internal const val DB_KEY_TWO = "dbKeyTwo"
internal const val DB_VAL_TWO = "dbValTwo"
internal const val CUSTOM_KEY_ONE = "customKeyOne"
internal const val CUSTOM_VAL_ONE = "customValOne"
internal const val CUSTOM_KEY_TWO = "customKeyTwo"
internal const val CUSTOM_VAL_TWO = "customValTwo"

internal const val DEFAULT_TOPIC_PREFIX = ""
internal const val MSG_CONFIG_PATH = "messaging"
internal const val DB_CONFIG_PATH = "database"
internal const val CUSTOM_CONFIG_PATH = "custom"