package net.corda.applications.workers.db.test

internal const val FLAG_INSTANCE_ID = "-i"
internal const val FLAG_TOPIC_PREFIX = "-t"
internal const val FLAG_MSG_PARAM = "-m"
internal const val FLAG_ADDITIONAL_PARAM = "-c"
internal const val FLAG_DISABLE_MONITOR = "-d"
internal const val FLAG_MONITOR_PORT = "-p"

internal const val KEY_INSTANCE_ID = "instanceId"
internal const val VAL_INSTANCE_ID = "123"
internal const val KEY_TOPIC_PREFIX = "topicPrefix"
internal const val VALUE_TOPIC_PREFIX = "abc"
internal const val MSG_KEY_ONE = "msgKeyOne"
internal const val MSG_VAL_ONE = "msgValOne"
internal const val MSG_KEY_TWO = "msgKeyTwo"
internal const val MSG_VAL_TWO = "msgValTwo"
internal const val EXTRA_KEY_ONE = "xtraKeyOne"
internal const val EXTRA_VAL_ONE = "xtraValOne"
internal const val EXTRA_KEY_TWO = "xtraKeyTwo"
internal const val EXTRA_VAL_TWO = "xtraValTwo"

internal const val MSG_CONFIG_PATH = "custom"
internal const val CUSTOM_CONFIG_PATH = "custom"
internal const val DEFAULT_TOPIC_PREFIX = ""