export const MESSAGE_SEND_FLOW_POLLING_DELETE_TIMEOUT = 10000;
export const FETCH_MESSAGE_FLOW_POLLING_DELETE_TIMEOUT = 5000;

//how often we call the flow to request all messages
export const FETCH_MESSAGE_FLOW_POLLING_INTERVAL = 10000;

export const FETCH_MESSAGES_AFTER_SEND_FLOW_MS = 500;

export const MESSAGE_SEND_STATUS_POLL_INTERVAL_MS = 2000;

export const FETCH_SEND_MESSAGE_FLOW_STATUS_POLLING_INTERVAL = 2000;
