/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.corda.p2p.markers;
@org.apache.avro.specific.AvroGenerated
public enum Component implements org.apache.avro.generic.GenericEnumSymbol<Component> {
  LINK_MANAGER, GATEWAY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Component\",\"namespace\":\"net.corda.p2p.markers\",\"symbols\":[\"LINK_MANAGER\",\"GATEWAY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
