@Library('corda-shared-build-pipeline-steps@ronanb/INFRA-1643/create-nightly') _

cordaNightlyPipeline(
    nexusAppId: 'flow-worker-5.0',
    runIntegrationTests: true,
    publishRepoPrefix: 'corda-ent-maven',
    createPostgresDb: true,
    publishOSGiImage: true
    )

