{
 "title": "Corda Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Message Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Durable Pattern Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(corda_messaging_processor_time_seconds_sum{messagePatternType=\"Durable\"}[$__rate_interval]) / rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"Durable\"}[$__rate_interval]) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Durable Pattern Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"Durable\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "State And Event Pattern Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(corda_messaging_processor_time_seconds_sum{messagePatternType=\"StateAndEvent\"}[$__rate_interval]) / rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"StateAndEvent\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "State and Event Pattern Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"StateAndEvent\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PubSub Pattern Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(corda_messaging_processor_time_seconds_sum{messagePatternType=\"PubSub\"}[$__rate_interval]) / rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"PubSub\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PubSub Pattern Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"PubSub\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compacted Pattern Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "rate(corda_messaging_processor_time_seconds_sum{messagePatternType=\"Compacted\"}[$__rate_interval]) / rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"Compacted\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compacted Pattern Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum(rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"Compacted\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Responder Pattern Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rate(corda_messaging_processor_time_seconds_sum{messagePatternType=\"RPC\", operationName=\"rpcResponder\"}[$__rate_interval])/ (rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"RPC\", operationName=\"rpcResponder\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Responder Pattern Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "sum(rate(corda_messaging_processor_time_seconds_count{messagePatternType=\"RPC\", operationName=\"rpcResponder\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(corda_http_server_request_total[$__rate_interval]))",
       "legendFormat": "RPS"
      }
     ]
    },
    {
     "title": "HTTP Server Requests Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(corda_http_server_request_time_seconds_sum[$__rate_interval]) / irate(corda_http_server_request_time_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sandbox",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sandbox Creation Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(corda_sandbox_create_time_seconds_sum[$__rate_interval]) / irate(corda_sandbox_create_time_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sandbox Creation Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(corda_sandbox_create_time_seconds_count[$__rate_interval]))",
       "legendFormat": "RPS"
      }
     ]
    }
   ]
  },
  {
   "title": "Flow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow Run Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(corda_flow_run_time_seconds_sum[$__rate_interval]) / rate(corda_flow_run_time_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Flow Run Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(corda_flow_run_time_seconds_sum[$__rate_interval]) / rate(corda_flow_run_time_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Uniqueness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uniqueness Client Request Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(corda_ledger_uniqueness_client_run_time_seconds_count[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uniqueness Checker Results (Running Total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum by(result_type) (corda_uniqueness_checker_request_count_total{result_type=\"UniquenessCheckResultSuccessImpl\"}) > 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(result_type) (corda_uniqueness_checker_request_count_total{result_type!=\"UniquenessCheckResultSuccessImpl\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uniqueness Client Run Time (Success Events)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(quantile) (corda_ledger_uniqueness_client_run_time_seconds{result_type=\"UniquenessCheckResultSuccessImpl\"}) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uniqueness Client Run Time (Failure Events)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(quantile) (corda_ledger_uniqueness_client_run_time_seconds{result_type!=\"UniquenessCheckResultSuccessImpl\"}) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uniqueness Checker Batch Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(corda_uniqueness_checker_batch_execution_time_seconds_count[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uniqueness Checker Sub-batch Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(corda_uniqueness_checker_subbatch_execution_time_seconds_count[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uniqueness Checker Batch Execution Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(quantile) (corda_uniqueness_checker_batch_execution_time_seconds) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uniqueness Checker Sub-batch Execution Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(quantile) (corda_uniqueness_checker_subbatch_execution_time_seconds) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uniqueness Checker Batch Sizes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum by(alias) (rate(corda_uniqueness_checker_batch_size_sum[$__rate_interval])) / sum by(alias) (rate(corda_uniqueness_checker_batch_size_count[$__rate_interval]))",
       "legendFormat": "Average Batch Size"
      },
      {
       "expr": "max by(alias) (corda_uniqueness_checker_batch_size_max) > 0",
       "legendFormat": "Max Batch Size"
      },
      {
       "expr": "sum by(alias) (rate(corda_uniqueness_checker_subbatch_size_sum[$__rate_interval])) / sum by(alias) (rate(corda_uniqueness_checker_subbatch_size_count[$__rate_interval]))",
       "legendFormat": "Average Sub-batch Size"
      },
      {
       "expr": "max by(alias) (corda_uniqueness_checker_subbatch_size_max) > 0",
       "legendFormat": "Max Sub-batch Size"
      }
     ]
    },
    {
     "title": "Backing Store Session Execution Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(quantile) (corda_uniqueness_backingstore_session_execution_time_seconds) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backing Store DB Commit Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(quantile) (corda_uniqueness_backingstore_db_commit_time_seconds) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backing Store DB Read Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(quantile) (corda_uniqueness_backingstore_db_read_time_seconds) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backing Store Transaction Attempts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "(sum by(alias) (rate(corda_uniqueness_backingstore_transaction_attempts_sum[$__rate_interval]) > 0)) / (sum by(alias) (rate(corda_uniqueness_backingstore_transaction_attempts_count[$__rate_interval]) > 0))",
       "legendFormat": "Average"
      },
      {
       "expr": "sum by(alias) (corda_uniqueness_backingstore_transaction_attempts_max) > 0",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Backing Store Errors (Running Total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "sum by(error_type) (corda_uniqueness_backingstore_transaction_error_count_total)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Put",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "irate(corda_cache_puts_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "irate(corda_cache_gets_total{result=\"hit\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "irate(corda_cache_gets_total{result=\"miss\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Eviction",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "irate(corda_cache_evictions_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
     "targets": [
      { "expr": "corda_cache_size", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}