/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155TokenSol from "./ERC1155Token.sol";
export type { erc1155TokenSol };
import type * as erc20TokenSol from "./ERC20Token.sol";
export type { erc20TokenSol };
export type { Storage } from "./Storage";
