@Library('corda-shared-build-pipeline-steps@feature/CORE-16419-isolated-sm-db') _

endToEndPipeline(
    assembleAndCompile: false,
    dailyBuildCron: '',
    multiCluster: false,
    gradleTestTargetsToExecute: ['smokeTest', 'e2eTest'],
    usePackagedCordaHelmChart: false,
    // TODO - remove this when J17 is the default in the pipeline
    javaVersion: '17'
)
