//placeholder pipeline WIP for e2e tests

pipeline {
    agent {
        docker {
            image 'build-zulu-openjdk:11'
            label 'docker'
            registryUrl 'https://engineering-docker.software.r3.com/'
            registryCredentialsId 'artifactory-credentials'
            // Used to mount storage from the host as a volume to persist the cache between builds
            args '-v /tmp:/host_tmp'
            // make sure build image is always fresh
            alwaysPull true
        }
    }

        triggers {
            cron '@hourly'
        }

    environment {
        ARTIFACTORY_CREDENTIALS = credentials('artifactory-credentials')
        CORDA_ARTIFACTORY_USERNAME = "${env.ARTIFACTORY_CREDENTIALS_USR}"
        CORDA_ARTIFACTORY_PASSWORD = "${env.ARTIFACTORY_CREDENTIALS_PSW}"
        CORDA_USE_CACHE = "corda-remotes"
        KUBECONFIG=credentials("e2e-tests-credentials")
        CORDA_CLI_USER_HOME="/tmp/corda-cli-home"
        GRADLE_USER_HOME = "/host_tmp/gradle"
        CORDA_REVISION = "${env.GIT_COMMIT}"
        NAME_SPACE = "run-${UUID.randomUUID().toString()}"
        BASE_IMAGE = "unstable"
        CLUSTER_NAME = "eks-e2e.e2e.awsdev.r3.com"
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '14', artifactDaysToKeepStr: '14'))
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
    }

    stages {
        stage('Prepare') {
            steps {
                sh 'mkdir -p "${GRADLE_USER_HOME}"'
                //download and set up CLI
                sh "curl -u '${CORDA_ARTIFACTORY_USERNAME}:${CORDA_ARTIFACTORY_PASSWORD}' https://software.r3.com/artifactory/engineering-tools-maven-unstable/net/corda/cli/corda-cli-developer/[RELEASE]/corda-cli-developer-[RELEASE].tar\\;source.branch+=main --output ./corda-cli.tar"
                sh "rm -rf ./corda-cli && mkdir ./corda-cli"
                sh "tar -C ./corda-cli --strip 1 -xf ./corda-cli.tar"
                sh "./corda-cli/bin/corda-cli -v"
            }
        }
        stage('Setup network') {
            steps {
               echo "add steps"
               sh './corda-cli/bin/corda-cli cluster configure k8s "${NAME_SPACE}"'
               sh 'echo """cluster:""" | ./corda-cli/bin/corda-cli --stacktrace cluster deploy -t "${BASE_IMAGE}" -c "${NAME_SPACE}" -f /dev/stdin | tee spec.yaml | kubectl apply -f /dev/stdin'
            }
        }
        stage('Wait for network') {
            steps {
                sh './corda-cli/bin/corda-cli cluster wait -c "${NAME_SPACE}"'
            }
        }
        stage('Forward ports and run the tests') {
            steps {
               echo "add steps"

                //for details see
                // https://github.com/corda/corda-runtime-os/blob/release/ent/5.0/applications/http-rpc-gateway/src/e2e-test/README.md


                sh '''
                    # Unfortunately port forwarding wasn't continued in the cli properly so this is a hack to make it work
                    forward_args=$(kubectl -n "${NAME_SPACE}" get pods -o=name | grep rpc | awk "{print \\\$1, \"8888\"}")

                    nohup kubectl port-forward -n ${NAME_SPACE} $forward_args > forward.txt 2>&1 &
                    procno=$! #remember process number started in background
                    trap "kill -9 ${procno}" EXIT

                    echo forward.txt
                    # Let the job populate the topics - this is bad
                    sleep 30

                    ./gradlew cleanE2eTest :applications:workers:release:rpc-worker:e2eTest
                '''
            }
            post {
                always {
                       echo "add steps"
                }
                success {
                        echo "add steps"

                }
            }
        }
    }
    post {
            cleanup {
                junit allowEmptyResults: true, testResults: '**/test-results/e2eTest/TEST-*.xml'
                archiveArtifacts artifacts: 'forward.txt', allowEmptyArchive: true, fingerprint: true
                sh 'rm -f forward.txt'
                sh 'kubectl delete ns "${NAME_SPACE}"'
            }
    }
}