/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models

import net.corda.httpclient.models.CreatePermissionType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The details of the permissions to be created along with existing role identifiers newly created permissions should be associated with.
 *
 * @param permissionsToCreate 
 * @param roleIds 
 */


data class BulkCreatePermissionsRequestType (

    @Json(name = "permissionsToCreate")
    val permissionsToCreate: kotlin.collections.Set<CreatePermissionType>,

    @Json(name = "roleIds")
    val roleIds: kotlin.collections.Set<kotlin.String>

)

