/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param major 
 * @param minor 
 */


data class ConfigSchemaVersion (

    @Json(name = "major")
    val major: kotlin.Int,

    @Json(name = "minor")
    val minor: kotlin.Int

)

