/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param signerSummaryHash 
 * @param version 
 */


data class CpiIdentifier1 (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "signerSummaryHash")
    val signerSummaryHash: kotlin.Any,

    @Json(name = "version")
    val version: kotlin.String

)

