/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *                  Details of the user to be created with the following parameters:                 enabled: If true, the user account is enabled; false, the account is disabled                 fullName: The full name for the new user                 initialPassword: The initial password for the new user;                      the value can be null for Single Sign On (SSO) users                 loginName: The login name for the new user                 parentGroup: An optional identifier of the user group for the new user to be included;                     value of null means that the user will belong to the root group                 passwordExpiry: The date and time when the password should expire, specified as an ISO-8601 string;                     value of null means that the password does not expire
 *
 * @param enabled 
 * @param fullName 
 * @param loginName 
 * @param initialPassword 
 * @param parentGroup 
 * @param passwordExpiry 
 */


data class CreateUserType (

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "fullName")
    val fullName: kotlin.String,

    @Json(name = "loginName")
    val loginName: kotlin.String,

    @Json(name = "initialPassword")
    val initialPassword: kotlin.String? = null,

    @Json(name = "parentGroup")
    val parentGroup: kotlin.String? = null,

    @Json(name = "passwordExpiry")
    val passwordExpiry: kotlin.String? = null

)

