/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *                  Details of the role to be created:                  roleName - name of the role                 groupVisibility - optional group visibility of the role             
 *
 * @param roleName 
 * @param groupVisibility 
 */


data class CreateRoleType (

    @Json(name = "roleName")
    val roleName: kotlin.String,

    @Json(name = "groupVisibility")
    val groupVisibility: kotlin.String? = null

)

