/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models

import net.corda.httpclient.models.FlowStatusResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param flowStatusResponses 
 */


data class FlowStatusResponses (

    @Json(name = "flowStatusResponses")
    val flowStatusResponses: kotlin.collections.List<FlowStatusResponse>

)

