/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fullHash 
 * @param groupId 
 * @param shortHash 
 * @param x500Name 
 */


data class HoldingIdentity (

    @Json(name = "fullHash")
    val fullHash: kotlin.String,

    @Json(name = "groupId")
    val groupId: kotlin.String,

    @Json(name = "shortHash")
    val shortHash: kotlin.String,

    @Json(name = "x500Name")
    val x500Name: kotlin.String

)

