/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The request sent during registration which contains the requested registration context map containing data required to initiate the registration process.
 *
 * @param context 
 */


data class MemberRegistrationRequest (

    @Json(name = "context")
    val context: kotlin.collections.Map<kotlin.String, kotlin.String>

)

