/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param permissionString 
 * @param permissionType 
 * @param groupVisibility 
 * @param virtualNode 
 */


data class PermissionSummaryResponseType (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "permissionString")
    val permissionString: kotlin.String,

    @Json(name = "permissionType")
    val permissionType: PermissionSummaryResponseType.PermissionType,

    @Json(name = "groupVisibility")
    val groupVisibility: kotlin.String? = null,

    @Json(name = "virtualNode")
    val virtualNode: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: ALLOW,DENY
     */
    @JsonClass(generateAdapter = false)
    enum class PermissionType(val value: kotlin.Any) {
        @Json(name = "ALLOW") ALLOW("ALLOW"),
        @Json(name = "DENY") DENY("DENY");
    }
}

