/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models

import net.corda.httpclient.models.MemberInfoSubmitted

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param availableNow 
 * @param memberInfoSubmitted 
 * @param reason 
 * @param registrationId 
 * @param registrationStatus 
 * @param registrationSent 
 */


data class RegistrationRequestProgress (

    @Json(name = "availableNow")
    val availableNow: kotlin.Boolean,

    @Json(name = "memberInfoSubmitted")
    val memberInfoSubmitted: MemberInfoSubmitted,

    @Json(name = "reason")
    val reason: kotlin.String,

    @Json(name = "registrationId")
    val registrationId: kotlin.String,

    @Json(name = "registrationStatus")
    val registrationStatus: kotlin.String,

    @Json(name = "registrationSent")
    val registrationSent: kotlin.String? = null

)

