/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models

import net.corda.httpclient.models.CpiIdentifier1
import net.corda.httpclient.models.Route

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cpiIdentifier 
 * @param routes 
 */


data class Routes (

    @Json(name = "cpiIdentifier")
    val cpiIdentifier: CpiIdentifier1,

    @Json(name = "routes")
    val routes: kotlin.collections.List<Route>

)

