/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *                  Information required to start a flow for this holdingId, including:                 clientRequestId: a client provided flow identifier                 flowClassName: fully qualified class name of the flow to start                 requestBody: optional start arguments string passed to the flow; defaults to an empty string             
 *
 * @param clientRequestId 
 * @param flowClassName 
 * @param requestBody Can be any value - string, number, boolean, array or object.
 */


data class StartFlowParameters (

    @Json(name = "clientRequestId")
    val clientRequestId: kotlin.String,

    @Json(name = "flowClassName")
    val flowClassName: kotlin.String,

    /* Can be any value - string, number, boolean, array or object. */
    @Json(name = "requestBody")
    val requestBody: kotlin.collections.Map<kotlin.String, kotlin.String>?

)

