/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.corda.httpclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Parameters for suspending or activating a member.
 *
 * @param x500Name 
 * @param reason 
 * @param serialNumber 
 */


data class SuspensionActivationParameters (

    @Json(name = "x500Name")
    val x500Name: kotlin.String,

    @Json(name = "reason")
    val reason: kotlin.String? = null,

    @Json(name = "serialNumber")
    val serialNumber: kotlin.Long? = null

)

