{{- if not or .Values.db.cluster.password.valueFrom.secretKeyRef.name .Values.db.cluster.password.valueFrom.secretKeyRef.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cluster-db" (include "corda.fullname" .) }}
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook": pre-install
  labels:
    {{- include "corda.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.db.cluster.password.value | b64enc | quote }}
  password: {{ required "Must specify db.cluster.password.valueFrom.secretRef.name or db.cluster.password.value" .Values.db.cluster.password.value | b64enc | quote }}
{{- end }}
