{{- if or ( not .Values.db.cluster.password.valueFrom.secretKeyRef.name) ( not .Values.db.cluster.username.valueFrom.secretKeyRef.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corda.clusterDbDefaultSecretName" . }}
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook": pre-install
  labels:
    {{- include "corda.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.db.cluster.username.valueFrom.secretKeyRef.name }}
  username: {{ required "Must specify db.cluster.username.valueFrom.secretRef.name or db.cluster.username.value" .Values.db.cluster.username.value | b64enc | quote }}
  {{- end }}
  {{- if not .Values.db.cluster.password.valueFrom.secretKeyRef.name }}
  password: {{ required "Must specify db.cluster.password.valueFrom.secretRef.name or db.cluster.password.value" .Values.db.cluster.password.value | b64enc | quote }}
  {{- end }}
{{- end }}
