apiVersion: v1
kind: ConfigMap
metadata:
  name: sasl
data:
  jaas.conf: |
    KafkaClient {
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username={{ .Values.kafka.sasl.username }}
        password={{ .Values.kafka.sasl.password }};
    };