{{- $name := include "corda.initialAdminUserSecretName" . }}
{{- $usernameKey := include "corda.initialAdminUserSecretUsernameKey" . }}
{{- $passwordKey := include "corda.initialAdminUserSecretPasswordKey" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook": pre-install
  labels:
    {{- include "corda.labels" . | nindent 4 }}
type: Opaque
data:
{{- if $existingSecret }}
  {{ $usernameKey }}: {{ index $existingSecret.data $usernameKey }}
  {{ $passwordKey }}: {{ index $existingSecret.data $passwordKey }}
{{- else }}
  {{ $usernameKey }}: {{ required "Must specify bootstrap.initialAdminUser.secretRef or bootstrap.initialAdminUser.username" .Values.bootstrap.initialAdminUser.username | b64enc | quote }}
  {{ $passwordKey }}: {{ .Values.bootstrap.initialAdminUser.password | default (randAlphaNum 12) | b64enc | quote }}
{{- end }}