{{- if .Values.kafka.sasl.enabled  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corda.fullname" . }}-kafka-sasl
  labels: 
    {{- include "corda.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.kafka.sasl.mechanism "PLAIN" }}
  jaas.conf: |
    KafkaClient {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username={{ .Values.kafka.sasl.username | quote }}
        password={{ .Values.kafka.sasl.password | quote }};
    };
  {{- else }}
  jaas.conf: |
    KafkaClient {
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username={{ .Values.kafka.sasl.username }}
        password={{ .Values.kafka.sasl.password }};
    };
  {{- end }}
{{- end }}
