{{- if .Values.kafka.sasl.enabled  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corda.fullname" . }}-kafka-sasl
  labels: 
    {{- include "corda.labels" . | nindent 4 }}
type: Opaque
stringData:
  jaas.conf: |
    KafkaClient {
        {{- if eq .Values.kafka.sasl.mechanism "PLAIN" }}
        org.apache.kafka.common.security.plain.PlainLoginModule required
        {{- else }}
        org.apache.kafka.common.security.scram.ScramLoginModule required
        {{- end }}
        username={{ .Values.kafka.sasl.username | quote }}
        password={{ .Values.kafka.sasl.password | quote }};
    };
{{- end }}
