apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-log4j" (include "corda.fullname" . ) }}
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook": pre-install
  labels:
    {{- include "corda.labels" . | nindent 4 }}
data:
  log4j2.xml: | {{ $.Files.Get "log4j2.xml" | nindent 4 }}
  {{- range $k, $v := .Values.workers }}
  {{- if $v.logging.override }}
  log4j2-{{ $k }}.xml: |
    {{- $v.logging.override | nindent 4 }}
  {{- end }}
  {{- end }}