{{- $_ := set . "worker" "p2pLinkManager" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "corda.workerName" . }}
  labels:
    {{- include "corda.workerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workers.p2pLinkManager.replicaCount }}
  selector:
    matchLabels:
      {{- include "corda.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "corda.workerSelectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- include "corda.imagePullSecrets" . | nindent 6 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/component"
                      operator: In
                      values:
                        - p2pLinkManager
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ include "corda.workerName" . }}
        image: {{ include "corda.workerImage" . }}
        imagePullPolicy:  {{ .Values.imagePullPolicy }}
        securityContext:
         allowPrivilegeEscalation: false
        {{- include "corda.workerResources" . | nindent 8 }}
        env:
        {{- include "corda.workerJavaToolOptions" . | nindent 10 }}
        args:
        {{- include "corda.workerKafkaArgs" . | nindent 10 }}
        volumeMounts:
        {{- include "corda.workerVolumeMounts" . | nindent 10 }}
        # Add health port when porting Link Manager to common worker framework CORE-4424
        {{- if .Values.workers.p2pLinkManager.debug.enabled }}
        ports:
          - name: debug
            containerPort: 5005
        {{- end }}
      volumes:
      {{- include "corda.workerVolumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}