{{- $_ := set . "worker" "p2pLinkManager" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "corda.workerName" . }}
  labels:
    {{- include "corda.workerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workers.p2pLinkManager.replicaCount }}
  selector:
    matchLabels:
      {{- include "corda.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "corda.workerSelectorLabels" . | nindent 8 }}
    spec:
      {{- include "corda.workerSecurityContext" . | nindent 6 }}
      {{- include "corda.imagePullSecrets" . | nindent 6 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/component"
                      operator: In
                      values:
                        - p2pLinkManager
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ include "corda.workerName" . }}
        image: {{ include "corda.workerImage" . }}
        imagePullPolicy:  {{ .Values.imagePullPolicy }}
        {{- include "corda.workerSecurityContext" . | nindent 8 }}        
        {{- include "corda.workerResources" . | nindent 8 }}
        env:
        {{- include "corda.workerEnv" . | nindent 10 }}
        args:
        {{- include "corda.workerKafkaArgs" . | nindent 10 }}
        {{- if not .Values.workers.p2pLinkManager.useStubs}}
          - "--without-stubs"
        {{- end }}
        volumeMounts:
        {{- include "corda.workerVolumeMounts" . | nindent 10 }}
        ports:
        {{- if .Values.workers.p2pLinkManager.debug.enabled }}
          - name: debug
            containerPort: 5005
        {{- end }}
          - name: health
            containerPort: 7000
        {{- if not .Values.workers.p2pLinkManager.debug.enabled }}
        livenessProbe:
          httpGet:
            path: /isHealthy
            port: health
          periodSeconds: 10
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /isHealthy
            port: health
          periodSeconds: 5
          failureThreshold: 20
        {{- end }}
      volumes:
      {{- include "corda.workerVolumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
