name: 'PR title check'
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.6.1
        with:
          title-regex: '^((CORDA|EG|ENT|INFRA|CORE|DOC|ES|DA5)-\d+)(.*)'
          on-failed-regex-comment: "PR title failed to match regex -> `%regex%`"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
